version: '3'
services: 
    web:
        image: nginx:1.19.10
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
    php:
        build:
            context: ./build
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'fe_db'
            MYSQL_PASSWORD: 'root'
            MYSQL_DATAbASE: 'fe_db'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
            #Host->mysql; root_user->root; pass->root
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
volumes:
    mysqldata: {}